CREATE TABLE rooms(
	id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	name VARCHAR(512) NOT NULL,
	capacity INT NOT NULL
);

CREATE TABLE users(
	id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	fullname VARCHAR(512) NOT NULL,
	email VARCHAR(512) NOT NULL
);

CREATE TABLE bookings(
	id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	room_id BIGINT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
	user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
	booking_date DATE NOT NULL,
	time_start TIMESTAMP,
	time_end TIMESTAMP
);





